[build]
  publish = "."
  command = ""

[[redirects]]
  from = "/health"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/chat"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"