# Netlify configuration - Redirect to FastAPI backend
# This site serves only the frontend, backend is deployed separately on Render

[build]
  publish = "."
  ignore = "/bin/false"  # Skip build entirely - this is just a redirect

[[redirects]]
  from = "/api/*"
  to = "https://nsw-revenue-ai-assistant.up.railway.app/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/health"
  to = "https://nsw-revenue-ai-assistant.up.railway.app/health"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"