services:
  - type: web
    name: answeringlegalquestions
    env: python
    plan: free
    region: oregon
    buildCommand: |
      echo "No dependencies needed - using only Python standard library"
      echo "Skipping all pip installations"
      python --version
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: APP_ENV
        value: production
      - key: LOG_LEVEL
        value: INFO
      - key: PYTHONPATH
        value: .
      - key: PYTHONUNBUFFERED
        value: 1
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
    healthCheckPath: /health
    autoDeploy: true