services:
  - type: web
    name: nsw-revenue-ai-assistant
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
      - key: OPENAI_API_KEY
        sync: false  # Set in Render dashboard
    healthCheckPath: /health