services:
  - type: web
    name: nsw-revenue-ai-assistant
    env: python
    plan: free
    region: oregon
    buildCommand: |
      python -m pip install --upgrade pip==25.2 setuptools==75.8.1 wheel==0.44.0
      pip install --no-cache-dir -r requirements.txt
    startCommand: python start.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: APP_ENV
        value: production
      - key: LOG_LEVEL
        value: INFO
      - key: PYTHONPATH
        value: .
      - key: PYTHONUNBUFFERED
        value: 1
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
    healthCheckPath: /health
    autoDeploy: true